services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI Management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  inventory-postgres:
    image: postgres:16
    container_name: inventory-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory -d inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 10

  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    volumes:
      - payment_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d paymentdb"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  order_pgdata:
  inventory_pgdata:
  payment_pgdata:
