# apps/inventory-service/src/main/resources/application.yml

server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/inventorydb
    username: devs
    password: Devel@ppeur1
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

